### ISSUE TITLE
latest-all.json.bz2 not found

### ISSUE THREAD

**Issue by vtnorton** [tom-james-watson/wikitrivia-generator#10]
Hey there, I'm trying to run on my computer the command described on the ReadMe file on the processing section, but it uses the `latest-all.json.bz2` file. Where can I get this file?

**Comment by vtnorton** [comment]
is this the file listed [here](https://dumps.wikimedia.org/wikidatawiki/entities/)?

**Comment by tom-james-watson** [comment]
Yeah that should be it :)

**Comment by tom-james-watson** [comment]
If you do run this, can you please pull latest `master`. I've made a commit that removes the user agent that identifies me specifically - https://github.com/tom-james-watson/wikitrivia-generator/commit/603fcf242318ba07d4a98af6169ebf549b00b049

You should replace it with something that identifies you and what you are doing.
